# Generated by Django 2.1.5 on 2019-02-10 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=255)),
                ('started_learning', models.DateTimeField(default=datetime.datetime(2019, 2, 10, 20, 27, 29, 281216, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=255)),
                ('guide_word', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLearnsLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.Language')),
                ('learner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.User')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('grammar_part', models.CharField(choices=[('ADJ', 'Adjective'), ('N', 'Noun'), ('V', 'Verb'), ('PREP', 'Preposition'), ('ADV', 'Adverb')], default='N', max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 2, 10, 20, 27, 29, 283227, tzinfo=utc))),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.Language')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.UserLearnsLanguage')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(through='lang.UserLearnsLanguage', to='lang.Language'),
        ),
        migrations.AddField(
            model_name='meaning',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.Word'),
        ),
    ]
