# Generated by Django 2.1.5 on 2019-03-13 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='started_learning',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 17, 50, 6, 525218, tzinfo=utc)),
        ),
    ]
