# Generated by Django 2.1.5 on 2019-03-13 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_auto_20190313_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='started_learning',
        ),
        migrations.AddField(
            model_name='userlearnslanguage',
            name='started_learning',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 17, 57, 2, 842849, tzinfo=utc)),
        ),
    ]
