# Generated by Django 2.1.5 on 2019-03-18 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0003_auto_20190313_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='topics',
            field=models.ManyToManyField(through='lang.WordHasTopic', to='lang.Topic'),
        ),
        migrations.AlterField(
            model_name='userlearnslanguage',
            name='started_learning',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 14, 48, 19, 329056, tzinfo=utc)),
        ),
    ]
