# Generated by Django 2.1.5 on 2019-03-24 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0004_auto_20190318_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='times_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlearnslanguage',
            name='started_learning',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 18, 54, 11, 593066, tzinfo=utc)),
        ),
    ]
