# Generated by Django 2.1.5 on 2019-03-24 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0006_auto_20190324_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearnslanguage',
            name='started_learning',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 19, 5, 39, 9230, tzinfo=utc)),
        ),
    ]
